import { PrismaClient, Role, InventoryStatus, RequestStatus, RequestType } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  const passwordHash = await bcrypt.hash('ChangeMe123!', 10);

  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@tsinglan.edu' },
    update: {},
    create: {
      email: 'admin@tsinglan.edu',
      displayName: 'Admin',
      passwordHash,
      role: Role.ADMIN,
    },
  });

  const teacherUser = await prisma.user.upsert({
    where: { email: 'teacher@tsinglan.edu' },
    update: {},
    create: {
      email: 'teacher@tsinglan.edu',
      displayName: 'Ms. Zhang',
      passwordHash,
      role: Role.TEACHER,
      teacher: {
        create: {
          title: 'Physics',
          department: 'Science',
        },
      },
    },
    include: { teacher: true },
  });

  const studentUser = await prisma.user.upsert({
    where: { email: 'student@tsinglan.edu' },
    update: {},
    create: {
      email: 'student@tsinglan.edu',
      displayName: 'Li Lei',
      passwordHash,
      role: Role.STUDENT,
      student: {
        create: {
          grade: 'G10',
          clazz: '10A',
          guardian: 'Li Parent',
        },
      },
    },
    include: { student: true },
  });

  await prisma.inventoryItem.upsert({
    where: { serialNumber: 'ASSET-0001' },
    update: {},
    create: {
      name: 'MacBook Pro 14',
      category: 'Device',
      serialNumber: 'ASSET-0001',
      status: InventoryStatus.ASSIGNED,
      assignedToTeacherId: teacherUser.teacher?.id,
    },
  });

  await prisma.venue.upsert({
    where: { name: 'Lecture Hall A' },
    update: {},
    create: {
      name: 'Lecture Hall A',
      location: 'Building 1F',
      capacity: 80,
      resources: 'Projector, Audio'
    }
  });

  if (teacherUser.teacher && studentUser.student) {
    const report = await prisma.report.create({
      data: {
        studentId: studentUser.student.id,
        teacherId: teacherUser.teacher.id,
        weekOf: new Date(),
        content: 'Weekly progress update for Li Lei',
        feedback: 'Keep up the good work',
      },
    });

    await prisma.request.create({
      data: {
        type: RequestType.LEAVE,
        status: RequestStatus.PENDING,
        reason: 'Medical appointment',
        studentId: studentUser.student.id,
      },
    });

    await prisma.aiRecord.create({
      data: {
        reportId: report.id,
        prompt: 'Summarize student weekly progress',
        response: 'Summary placeholder generated by AI',
        model: 'gemini-pro',
      },
    });
  }

  console.log('Seed completed', { adminUser: adminUser.email });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
